blogtest/blog/config/routes.rb
 Rails.application.routes.draw do
  
  resources :posts do
  	resources :comments
  end
  
  root "posts#index"
 
get '/about', to: 'pages#about'
end

blogtest/blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

blogtest/blog/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true,  length: { minimum: 5 }
	validates :body, presence: true
end

blogtest/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blogtest/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
	@post = Post.find(params[:post_id])
	@comment = @post.comments.create(params[:comment].permit(:name, :body))

	redirect_to post_path(@post)
end

def destroy
	@post = Post.find(params[:post_id])
	@comment = @post.comments.find(params[:id])
	@comment.destroy

	redirect_to post post_path(@post)
end

end

blogtest/blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController

def about
end



end

blogtest/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts =Post.all.order('created_at DESC')
	end	

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		
		if @post.save
		 redirect_to @post
		else 
			render 'new'
	end
	end
	
	def show
		@post = Post.find(params[:id])
	end
			
		def edit
			@post = Post.find(params[:id])
	end

		def update
			@post =Post.find(params[:id])

			if @post.update(params[:post].permit(:title, :body))
				redirect_to @post
			else
				render 'edit'
			end

		end
		
		def destoy
			@post = Post.find(params[:id])
			@post.destroy

			redirect_to root_path
		end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end

		end

blogtest/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blogtest/blog/app/helpers/c_omments_helper.rb
module COmmentsHelper
end

blogtest/blog/app/helpers/pages_helper.rb
module PagesHelper
end

blogtest/blog/app/helpers/posts_helper.rb
module PostsHelper
end

blogtest/blog/app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago
		</p>
	</div>

	<p><%= link_to 'Delete',[comment.post, comment], method: :delete, 
		class: "button", 
		data: { confirm: 'Are you sure?' } %>


	</p>
</div>

blogtest/blog/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</p>

<p>
	<%= f.label :body %><br>
	<%= f.text_area :body %>
</p>
<br>
<p>
	<%= f. submit %>
</p>
<% end %>

blogtest/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/
  cdd?family=Raleway:400,700' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%link_to root_path do %>
			 <%= image_tag "logo.svg" %>
			 <% end %>
			</div>

			<ul>
				<li class="category">Website</li>
				<li> <%= link_to "Blog", root_path %></li>
				<li> <%= link_to"About", about_path %></li>
			</ul>

			<ul>
				<li class="category">Social</ li>
				<li><a href="https://twitter.com/AeeDeeTee">Twitter</a></li>
				<li><a href="https://instagram.com/AeeDeeTee">Instagram</a></li>
				<li><a href="mailto:workwithamandataylor@gmail.com">Email</a></li>
			</ul>

			<p class="sign_in">Admin Login</p>
		</div>
<div id="mail_content">
	<div id="header">
		<% if current_page?(root_path) %>
		<p>All Posts</p>
		<% elsif current_page?(about_path) %>
		<p>About</p>
		<% else %>
		<%= link_to "Back to All Posts", root_path %>
		<% end %>
<div class="buttons">
	<button class="button"><%= link_to "New Post", new_post_path %></
		button>
		<button class="button">Log Out</button>
</div>
</div>
<% flash.each do |name, msg| %>
<%= content_tag(:div, msg, class: "alert") %>
<% end %>
<%= yield %>
	</div>

</body>
</html>

blogtest/blog/app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.jpeg" %>
	</div>

	<div id="content">
		<h1>Hey, I'm Amanda Taylor</h1>
		<p>Welcome to my blog</p>
	</div>
</div>

blogtest/blog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this 
				post from saving</h2>
				<ul>
					<% @post.erros.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
	<% end %>
<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
</p>

<p>
	<%= f.label :body %><br>
	<%=f.text_area :body %>
</p>

<p>
	<%=  f.submit %>
</p>

<% end %>

blogtest/blog/app/views/posts/edit.html.erb
<div id="page_wrapper">
<h1> Edit Post </h1>


<%= render 'form' %>
</div>

blogtest/blog/app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.created_at .strftime("%B, %d, %Y") %></p>
	</div>
<% end %>

blogtest/blog/app/views/posts/new.html.erb
<div id="page_wrapper">
<h1> New Post </h1>


<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this 
				post from saving</h2>
				<ul>
					<% @post.erros.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
	<% end %>
<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
</p>

<p>
	<%= f.label :body %><br>
	<%=f.text_area :body %>
</p>

<p>
	<%=  f.submit %>
</p>

<% end %>
</div>

blogtest/blog/app/views/posts/show.html.erb
<div id="post_content">

	<h1 class="title">
	 <%= @post.title %>
	 </h1>

	 <p class="date">
	 	Submitted <%= time_ago_in_words(@post.created_at) %> Ago
		| <%= link_to 'Edit', edit_post_path(@post) %> 	 
		| <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm:'Are you sure?' } %>
	 </p>

	 <p class="body">
	 	<%= @post.body %>
	 </p>

	 <div id="comments">
	 	<h2><%= @post.comments.count %> Comments</h2>
	 	<%= render @post.comments %>
	 	<h3> Add a comment </h3>
	 	<%= render "comments/form" %>
	 </div>
</div>